vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    images:
      uri_prefix: /images/produits
      upload_destination: "%kernel.project_dir%/public/uploads/images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
